add_test( [==[Swiftnet - Constructor]==] /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test/test-swiftnet [==[--test-case=Swiftnet - Constructor]==])
set_tests_properties( [==[Swiftnet - Constructor]==] PROPERTIES WORKING_DIRECTORY /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test LABELS)
add_test( [==[Swiftnet - Zero Padding]==] /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test/test-swiftnet [==[--test-case=Swiftnet - Zero Padding]==])
set_tests_properties( [==[Swiftnet - Zero Padding]==] PROPERTIES WORKING_DIRECTORY /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test LABELS)
add_test( [==[Swiftnet - weights init]==] /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test/test-swiftnet [==[--test-case=Swiftnet - weights init]==])
set_tests_properties( [==[Swiftnet - weights init]==] PROPERTIES WORKING_DIRECTORY /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test LABELS)
add_test( [==[Swiftnet - zero pad forward_pass WIDTH 64]==] /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test/test-swiftnet [==[--test-case=Swiftnet - zero pad forward_pass WIDTH 64]==])
set_tests_properties( [==[Swiftnet - zero pad forward_pass WIDTH 64]==] PROPERTIES WORKING_DIRECTORY /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test LABELS)
add_test( [==[Swiftnet - zero pad inference WIDTH 64]==] /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test/test-swiftnet [==[--test-case=Swiftnet - zero pad inference WIDTH 64]==])
set_tests_properties( [==[Swiftnet - zero pad inference WIDTH 64]==] PROPERTIES WORKING_DIRECTORY /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test LABELS)
add_test( [==[Swiftnet - Batch Sizes forward]==] /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test/test-swiftnet [==[--test-case=Swiftnet - Batch Sizes forward]==])
set_tests_properties( [==[Swiftnet - Batch Sizes forward]==] PROPERTIES WORKING_DIRECTORY /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test LABELS)
add_test( [==[Swiftnet - Net Widths forward]==] /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test/test-swiftnet [==[--test-case=Swiftnet - Net Widths forward]==])
set_tests_properties( [==[Swiftnet - Net Widths forward]==] PROPERTIES WORKING_DIRECTORY /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test LABELS)
add_test( [==[Swiftnet - backward different widths, weights, and batch sizes]==] /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test/test-swiftnet [==[--test-case=Swiftnet - backward different widths\, weights\, and batch sizes]==])
set_tests_properties( [==[Swiftnet - backward different widths, weights, and batch sizes]==] PROPERTIES WORKING_DIRECTORY /nfs/site/home/yuankai/code/tiny-dpcpp-nn/build_arc/test LABELS)
set( test-swiftnet_TESTS [==[Swiftnet - Constructor]==] [==[Swiftnet - Zero Padding]==] [==[Swiftnet - weights init]==] [==[Swiftnet - zero pad forward_pass WIDTH 64]==] [==[Swiftnet - zero pad inference WIDTH 64]==] [==[Swiftnet - Batch Sizes forward]==] [==[Swiftnet - Net Widths forward]==] [==[Swiftnet - backward different widths, weights, and batch sizes]==])
